before_install:
  - sudo apt-get install libdb-dev
services:
  - redis-server
language: ruby
rvm:
  - ree-1.8.7
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
notifications:
  recipients:
    - d.sukhonin@gmail.com
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
